# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 06:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('', 'Please Come Back at the Specified Time. For more details, visit Home Page')], default='NoAttendance', max_length=50)),
                ('t_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('only_date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
