# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20180224_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='only_day',
            field=models.CharField(default='Monday', max_length=30),
        ),
    ]
