# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_session_only_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='only_time',
            field=models.CharField(default='09:57:37AM', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning')], default='No Attendence', max_length=25),
        ),
    ]
