# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20180226_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='only_time',
            field=models.CharField(default='10:03:26AM', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(default=[('', 'Please Come Back at the Specified Time. For more details, visit Home Page.')], max_length=25),
        ),
    ]
