# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 05:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20180226_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='only_day',
            field=models.CharField(blank=True, default=26, max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='only_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning')], default='No Attendance', max_length=25),
        ),
    ]
