# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20180226_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='only_day',
        ),
        migrations.RemoveField(
            model_name='session',
            name='only_time',
        ),
    ]
